### ISSUE TITLE
Not working on Ubuntu deb package installe

### ISSUE THREAD

**Issue by gmstyle** [ju1ius/uxdgmenu#7]
Hi,
deb package installed on ubuntu with openbox but not working when i try to start daemon:

root@gabriele-Aspire-5810T:~# uxm-daemon start -f openbox
Traceback (most recent call last):
  File "/usr/bin/uxm-daemon", line 146, in <module>
    action(options)
  File "/usr/lib/uxdgmenu/uxm/daemon.py", line 14, in start
    update(opts)
  File "/usr/lib/uxdgmenu/uxm/daemon.py", line 49, in update
    update_bookmarks(opts)
  File "/usr/lib/uxdgmenu/uxm/daemon.py", line 77, in update_bookmarks
    data = parser.parse_bookmarks()
  File "/usr/lib/uxdgmenu/uxm/parsers/bookmarks.py", line 39, in parse_bookmarks
    icon = self.icon_finder.find_by_file_path(path) if self.show_icons else ''
  File "/usr/lib/uxdgmenu/uxm/icon_finder.py", line 67, in find_by_file_path
    return self.find_by_mime_type(str(mime_type))
  File "/usr/lib/uxdgmenu/uxm/icon_finder.py", line 60, in find_by_mime_type
    return self.lookup(default).encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

can someone help me?

thanks

**Comment by ju1ius** [comment]
Hi,
Thanks for taking time to report this issue.

The error is caused by uxdgmenu not being able to find the default icon (the default icon name was not found in your selected icon theme).
Before going further, it's important to mention that uxm-daemon is a user-space daemon and must not be run as root, because menus, icons, etc are user-specific preferences (unless you run your whole X session as root, which is really not a good idea). Moreover, the root user's GUI preferences (especially the GTK icon theme) are often not set by default on a fresh linux distro install.

So my advice is that you first try to run the daemon as a normal user.
If the problem persist, try setting the default icons in the [configuration](https://github.com/ju1ius/uxdgmenu/wiki/Configuration) to something existing.
For example to look for a default application icon, you could run

``` sh
$ find /usr/share/icons -name "application-x-executable*"
# or restrict to a particular theme
$ find /usr/share/icons/YOUR_THEME_NAME -name "application-x-executable*"
```

If you can't find anything, I suggest you install the `gnome-icon-theme` package, which contain sensible defaults.

That being said, the application die like this, so I'll be working on fixing this issue ASAP!
